apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: PLACEHOLDER_NAMESPACE
spec:
  template:
    spec:
      containers:
        - name: server
          ports:
            - name: http
              containerPort: 8080