prometheus:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false
  prometheusSpec:
    storageSpec: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

grafana:
  enabled: true
  defaultDashboardsEnabled: false
  adminPassword: "admin"
  service:
    type: ClusterIP
  ingress:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true

alertmanager:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
