---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook-slo-alerts-prod
  namespace: monitoring
spec:
  encryptedData:
    url: AgBqj2oBzrJdPIXS0kPqUZhp2LYMhnDpEPLP+FAoYDxYppvdSGdwoj36W+H95sk3XKVk821WFPlOltOPxOmZXGpMV3ZdkXfiz0Be5e7J6hI8usuTkp7O+BINsmrQzVADmDCaDhsefvbRQwX2uUNKpBjjDVx5SlQUFhfWtuPl6yC9KpUCQvYADvDnvIYCw++jcWHTTm9RDQF6CIU9Nk24zOsNgylqH3jzwE3cHGtnZ0qisrBIffQCRDZ5vA+p8gR/iYr5zabdD9DC87h96UfZOMFcAdlDoBEBu7rFmMGrquBEehl7L+p1rCrxzqTJ6q3gnHKyKVGUpaty3LmM/dJU7j76gNN8SIFRUDgZTFg2Vlc/vI9npfJPltsMkC1micj1wcpV3tbY7LS7gZQ66anP4ordzUKriHmZsVoj6Z+rFK8Y2RPuaw/J/TrQHfHGHjcl9sGxO2OJ5P/DdEoYdwtMt0M6lZzmFRQv75PO+DaSrl9hC2vpHfoFNJWwR13l34vvlxXCZsgkm2UzkN/Qo0Zi4Fz2R8TtdpCNc/wJVajfvknoghkLzs2ZfIZta0/aPO65+U0fjT32FSUVQs6XDI0TyE+xH8iVrFTWGD3B6zxiqkhimkgCYRxCuJfdODpOCD5XunqSbVhKThy7Wp9ixuNQEVW0/6RtpEYahoE+YC+WXC3XnCE7/6WLIhd5pthkQc/I5/HeDi2P3v9vC5vhkJrdtTeuGTafTryZ7GIL2IGmyW2y99svXkLwYd4qC8+2zMnei5GFKGCPEj9RAXyOKTaqbgWfVZHUPCWcf/M8kdx+m7MSstc8
  template:
    metadata:
      name: alertmanager-slack-webhook-slo-alerts-prod
      namespace: monitoring
