---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook-service-alerts-prod
  namespace: monitoring
spec:
  encryptedData:
    url: AgBoVuUfq4/dFbwNh5q2HIMqZ2oFlqvozST3C4PKpXEd2OA5m4sSjRMSn0zpm7jTDHbEoeZULhXJqTXLeWyj1/Nw/cfl70bFXCqVtN2lWvsggxrLQp2w1rwbaJEPZOwP3vmla7lhb/ck813VhTPhrCpvSGv4apCkSb1hSUBx01ImAb1dAlS98B6acYabMAQx9A4iI/gBUWCkmy6gWNKIq00B1Lnr0kAVZwujesD/UFiRtoq+SGn4xz04ImyFJbANO3Jx4iXoKnHdUZu2HBlItSwQ99ZPHkhE3XdTeLDoAitJrGptascjuOvFCDDA5Bqb1iWp4xGvJP3uJrdDCPDTEJSWWNCaNt1iAkNz9gZaBho4jrmH308PBt+k4nkPYBSFo8R3iupmp5E6zemEq1RZN82XCVItRuChTeYOBjDzmgoCY7h7KeA0bLZ6LwT1ndySnKV72Yc3uLEmduynwXOeFlQd5q4SHkgdiUCJ/YBLrb3Nr5wf7Dl/dlAreZOXddqKMLB8uVEc/VCXf5BTMW+YNA1KJfIMUAOkzTK92nctjWu+E5wmQECv02DJIcW80Voi4oy7Bh5wcv6uAfxZc0ElMDbEHkiFwpe7zR+lg8HWUIy1rsYaPC+aJyo4uu9NUyuV2/MuYW2WvdpGx/zW4qKpq6CQ7tbV7rlkDkx6fdsTkuHqpSVKxQGzAsw69cNb7KQTDUcw2FKGlzwyx47LzD4DQuEjP5aFklGAIz89BBJmFvmDOIFW51FEomWrsglWFkm+/FQmomrwiKlWmxklqOWclitgdsKgfogaIEUyEgzigvIwvaLx
  template:
    metadata:
      name: alertmanager-slack-webhook-service-alerts-prod
      namespace: monitoring
