---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook-platform-alerts-prod
  namespace: monitoring
spec:
  encryptedData:
    url: AgBowq93eGYi8NlVWavpP5GkGyd49UMYD9VTDYBGLlYMhr2ykFFFqyXwE5jTWifXEUqzFy2uZWMlOo6nV40R4WKPouUv5wxTxZvh7BSAYOviXP2I5mAjws24p2aErB9WfQt615rOXFA9VvBd4+nRSxT6ZZZ1hlqsRXmpqjns6TuRWf0XV7NxW/OhNvc0nOS9uWbREFjWUv4cWeFxL6r0FPCdTTDn3SWelvCy7iSMC8IWvaMraJFpe1m/97eK8Xk6j6F04QOc5bpGAiZIcGfz5NFwr2pT8JCEzS88sRuwIw33PT7BmDNvCrJPppJQxU2LRGTbOULpqCoCLxDROccOO/K5mEkhEvOPPtP+y/qmiMgyjWxN4kLGVuNshW3sjAGhCccvr3bTExNjxEE5x+Cb0/cNpZV9RxJQtGYCuSXUtLEMm/OgHOSWW/7fD3ewXZ5wUP+bBBm0PpmvWuSZx8vO1H3vz2XY7RcKAIOgN/tRK6YTjiIdcE9Fs+32oKlSO//fwdy4oJrtY5sRUxxJAmeRfR+4pxrir+m+1JOluH1JZk4RAMLOutGQD2FRmyYybtZnArifWtQPjiGnDxim6c4jUgPm94Btckw1/i7Y1M+KchAdZwtm7hu/tKhZRV8GCgFdXPOiKH0+XODR6FzK22xAA+qovOzSnwp6DBBrezJKIseuz9lvjpsOSJf/gQnhTrhXs9axu+rfepiO0Ru6xWs1tPkumyxcBvV5vgCkd4uQrr8PoWKnI5dbWapAGcKDjkHRkxO9X/nNecLyclugPcD07cj6Toz64P2fJcmEWc6Er3KIDXgS
  template:
    metadata:
      name: alertmanager-slack-webhook-platform-alerts-prod
      namespace: monitoring
