---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgBB/w1TwAHMxl+Xc8GC2TW5JZnyuop3zhpCkKBkYUvzKV+zQPklIsOJ0Nio5ODg/asDVgGDIf9sRBbVnuG+0s/LeyWjz6GzDOWY6uRplF/0qQrKtkTOQeIlD52dccgsvLZpkXpFf2xs8AodcWb2wkuTS6lBaLBCvqToRHqJ7Z21YSwN9pRSgItHk7pk30x6V0spE+9sec05e3Gmm2JmZ5i/IBNM9QkQnZB9PthBuRxbm+D9qjSGWlO4sFHW7snTpX+RVK1ckOlG2AjI01JlrkS8TiY5TwrlySklVYOwj3pRSMQrzJBaX3Nnf6cUh1UbvMFhhBoDVUjO/gIqzhEIt9Tvciec0RUQg4VVwyczo8Xkeuo3tVSuSb0VZv0nj3g8Ep77hi1SHMAomPywNikfnmhWwh8F00bb3Yrc9h7nWafKUEU9of8aMJFdtp1YhtjB7Kux37SGyXwK0WWTWbBxN98XBHTW4dVeI5akRCs2m73Nwu1m88cwZb+fOZ5K182xbIMliA0CbHQbciBgiFfIppD1/fOIVTJgM3hy2w5D2wqk4oLgzayKUiv+tbTr0qaa0r8/if4wdmQVCJDA2NdRUXfDgOthaQBc3JoYVEAFaQIn+gpQ1KFdY+qie6TBWYvKebl+XJZmS1jbbNqzl56huyA7QXtmfvU1vsMyCR3KzWMK9muFkXlz66qnPXzi2L6ibdPTViir1GzHXdfhW86tdOyH8v4wzNQAG8zET9o4pzXKcQU4K8Hk/naRdo74T+zJiLylgqHU8mJ5ci3OXCJlKijFm05SA1bjNMIRySHdQAGubw4=
  template:
    metadata:
      name: alertmanager-slack-webhook
      namespace: monitoring
