---
prometheus:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false
  prometheusSpec:
    storageSpec: {}

grafana:
  enabled: true
  adminPassword: "admin"
  defaultDashboardsEnabled: false
  service:
    type: ClusterIP
  ingress:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      provider:
        foldersFromFilesStructure: false
    datasources:
      enabled: true
      label: grafana_datasource

alertmanager:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
