---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook-service-alerts-dev
  namespace: monitoring
spec:
  encryptedData:
    url: AgBagGIe+CUImtgNF3lGIPMbB2Mm0rvYf/0+ZxjSJF0yXWD8S3dsxFN4GoYHo3aKLEbXP9dD52ldUSVeJNQUZGa0gl8sDZ9vJ5L/BJbvsou94Fpo/IzhfE/NaLO0mGcMJRPvvt6clafzyb4T91dpQA1IyQ2ugqQmym/nyubfzYGTW8w7sXiMIoed2mH+3TEup3Xw/Pgo8Mm/98vFIgrBJF8znkNvPnCcUI+fJm3xywOjcSXMVPG1H2xzmOJI5/d41QYuD/nGKqnN3oJ89J/hzuz2T4cBsvq7J6df8mVtTuFe0BDQ5uv7okc81U8tpEzOUcRa8YqCl4gUxyE04gZaPTbLwmuFU2lA2GWBtQXgJECGMBAOz+C2xzVfmkUijMEeNh9oGHmdXb8vpIf4LO8stD8baP9Mj1XXZRhHV/ooLXEEvlUHrDLxCH+uMoWn69XhrzyTW0XNNfizZ3gCfYOemiwkQLIl4oC3m1/wuhC6hfJ+TjsdVSZwUIiB8VQKrJkrsuWiJ19XfGShlTaNbw1olEpZCZ7d7xPblvMvvDL8LssShmp3fav2cTBUxqSge8BtAYOdOf2uhPqn4O2nBdntH7sY+hctN+hfvNgVAE7hgj47//e2M+IjZewf8lBXWOPEzbq+CEHFwIF1nTXOb0fH+0QT/tWU7oApu1SCs8o9d4t1nXqTOg4687Io+aRgGSNXaUlBMg7jxB2VuCzZvTp2dlF6c9dwZGravPfgz2X2nhOap4vRZZxfz/XLlxe75wnCY+RxDlvhbzKLVZPoUzOTQ7wxU/i5EwMcfQHy2WKV3t4Y+8Yo
  template:
    metadata:
      name: alertmanager-slack-webhook-service-alerts-dev
      namespace: monitoring
