---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook-slo-alerts-dev
  namespace: monitoring
spec:
  encryptedData:
    url: AgBruM39wedn/e62clP0J0PASRShJZahKxAD5s8J/k30ekcxbABxFj0aB7PYOOw1SKa/t5inadHVk4+x/Ld7877XAKKFszdyLx4jENfMrTYNfw1iZAi28A3nHMf/MiYOFiCHs9+Zo3kYKPk/FMiYVGPzESF8xQjGW3MxcVLWa4jhzkOzoDLe67pUQzuvFWpw4droY6W3p9EquMRxw66Jx0kmxefdrL6PsBWe3LMmM7g+yEbf7QrD8FrUQRLfB9eoaOgOAL6CZGd++9gmAWxFVgXM47p/1JAHSLbYoPvpL61CYXKhABp/7xhyr1sQwrD/1zTDXCzRiO787YGY9M80PQXh2rhNt0H8a8YgG7vT7fyD/XkvhgkZdsQx/7j7CmRKp+qIqzNhrJUf0MXkexhUMKtCouTV9Bcdenu2sTWEH2MfAMJqpXXSh4T6JoT8YZIN6/9weOruhXPcUBAvQFZOdKpH0YRp9Nf6ge632mAM8cBcpmB6G7AbKyoEhroLDLvY00/3QePZQnu17RLHczH1XlOeUfj6NnvhaiiAfiYONjdNqaBa/7TiQocSAS2Rg+o1X2s4Ln5OYqwrx7I/FDQBaeAXFR71SvqtwZY/SUudZeD7tgKX0SV92L/cKiuJo8xmYE1btNVZyWah0UFsbszTJkNXLK34gOcQPGd04mppp4V4DNud2hQd74TtqAP+hdPB25l46FLkgJnvcXHn72j2nIXzHwZ+XSmQuFF8Kxe72ySedDZzsG7cyIzCja1Yqdgv4HyFxKQbjdx+oOKSSMwqVusrkm8A7p2S44DRtqF4VJbQo0qK
  template:
    metadata:
      name: alertmanager-slack-webhook-slo-alerts-dev
      namespace: monitoring
