---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook-platform-alerts-dev
  namespace: monitoring
spec:
  encryptedData:
    url: AgBagBFGWmuPCjtc+x+Kjp/Uf+DWZbNvBd2U6z6GdcgdFoIJ2gJp7poisMFEuN9VS337ASK2PEClJpo5zQA/JRQhRz68Fx6cCPmaFg/o/JAoVhXRhsZAuzXMOcWtA+TGyFn2fqQNG2/BoR5/4OWot3RWr82gC7s/YI/tjaHH7EY6y09xyduYQYWC/fvtiw1k+z7nLqOsY+QVKYLzt6gQSaaVDLNjCdCN6c0wv56mTTBfC8p/MFB19hu+pOIdJa4ieb8sRdbJkysmqA4qbud5cPjOPJztDr5hDpQQazAfxOCvCggpzfvQlb64C6CKUQPewghy3Jx6cky2MNAYr/m5fhkxZ9s+zcwnfqfcSTeQBTjmMpTHozGCxXLFKVSM4SbTwzag7nSiS07AxxuQDTcZrxA/isiq+YQUd1McIRJVPWDJOS5PO3Gx9mxBxdyg3JrCCOc0x5QzXy2c1mgFWXEcX6LxdhQ9sPUFx5xS509Z0yzpzLTlE1DEwZBKSxhMTQSUIqRYDGkb1pYLDrzOJj4iKrQUaUuK7xGtctBe00ocFLR1LrKP24dVgRW+4cwZZRN2aoXVSJ4t4MyrZAwbbAs5wyyESCatpkzFZWJeVKJhtpLClPy1hWXKh7t9he7f4T1Slo3cWPGyAp7+8hjq5PQDn4helfxF3tGIGFcsUsegvLlb5PbmUAtku+sq/0NqIMt1aS7TGXs+iztfWsIkbiA/QSJZ2d3ClfegL1/9CYqgbAq8DE/2fjffW24ql6ZAbB4MpnbFONTbLAW7Iz2n0JgnaOvqtNSCyjtlFztesrDiCi0D2TWN
  template:
    metadata:
      name: alertmanager-slack-webhook-platform-alerts-dev
      namespace: monitoring
