---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgAKNUi7d2WeTd4ItQu7yjFpDxhaak5Fb1XPeNhLPb8aIGXNH5trVsDLWKUFrm4f4jDLGFXWqkmH1OS22hW/870HKqF2fQVCI8ujxyg8O7GpYmUCh1nDipLlpt8nrPh7+IDkcYtrwhhfmuu1OphHXj2RR4clKE8PFojGHUhk5rZISy0niw2qSESql4xfwGCZci1Xh+5jYdwQMdY+4hwuvDD7zcJjUq7QoHTlCJrGW6f5zvkzh3Mte9uDGIeOUNUbUAq7+uTY01NHwJlqgvzlnN7Lh1qw8GmHzyuIvv9fe57TwRgyRuna+5dYKb3q8vcwigTSxLYuiRkDmpa03gBrvE9spfyHlwCkMkOrk/VeLsHYnoZ45zH25b9ti1IXa/BOM9NfhozzxCjTa2e+qNmkxsuJvMnwXNQA7V5NsiFEPE/Tp31fUB0EDjPSzYRogO0bQR9eXsy2FBi4ht29c+ugMXSLX4lyirqARW/psRL/v2v3+9lOKhig2YWQsIecW9HQJU7nQxqBGOrHKoHMRWrdO6y2bAW6f3nk61a/Fw8WHKSpNQ0CnQIyKlK0tjF72Mw3kNoPT69LYAOEC7dihQQAjRwVT7f5iyUy2p9DMfXyfnQC3K1KKTCxOxMozbKcvQt835V4PWhX41mv33k5/nZQTMhpO5WDgArp78Ud8sLZ9jnXOqrcHVkH6lyyVGRdSZ+yAZ2YyVEtCmvpnLBY0yArBO/BRoK0DBEG/B0iM1gbDwjXlUEYnNDiGuxZa89QOHsH64OrjNJbBD7mvt7DB4Lgu0tvzaFFkOQcNRsdItJK3nV8ylI=
  template:
    metadata:
      name: alertmanager-slack-webhook
      namespace: monitoring
