---
prometheus:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false
  prometheusSpec:
    ruleSelector:
      matchLabels:
        release: kube-prometheus-stack

grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: ClusterIP
  ingress:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true
      label: grafana_datasource
  defaultDashboardsEnabled: false

alertmanager:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchLabels:
        release: kube-prometheus-stack

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
