apiVersion: v2
name: prometheus-stack
version: 0.1.0

dependencies:
  - name: prometheus
    version: "29.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled

  - name: kube-state-metrics
    version: "5.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-state-metrics.enabled

  - name: prometheus-node-exporter
    version: "4.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus-node-exporter.enabled
