apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

configMapGenerator:
  - name: grafana-dashboard-emojivoto
    files:
      - dashboards/emojivoto-voting-dashboard.json

  - name: application-reliability
    files:
      - dashboards/application-reliability.json

  - name: aws-alb-cloudwatch-metrics.json
    files:
      - dashboards/aws-alb-cloudwatch-metrics.json

  - name: node-exporter-full.json
    files:
      - dashboards/node-exporter-full.json

  - name: loki-kubernetes-logs.json
    files:
      - dashboards/loki-kubernetes-logs.json

  - name: kubernetes-views-global.json
    files:
      - dashboards/kubernetes-views-global.json

  - name: kubernetes-views-namespaces.json
    files:
      - dashboards/kubernetes-views-namespaces.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"