---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- alerts

configMapGenerator:
  - name: grafana-dashboard-emojivoto
    files:
      - dashboards/emojivoto-voting-dashboard.json

  - name: application-reliability
    files:
      - dashboards/application-reliability.json

  - name: aws-alb-cloudwatch-metrics.json
    files:
      - dashboards/aws-alb-cloudwatch-metrics.json

  - name: node-exporter-full.json
    files:
      - dashboards/node-exporter-full.json

  - name: loki-kubernetes-logs.json
    files:
      - dashboards/loki-kubernetes-logs.json

  - name: kubernetes-views-global.json
    files:
      - dashboards/kubernetes-views-global.json

  - name: kubernetes-views-namespaces.json
    files:
      - dashboards/kubernetes-views-namespaces.json

  - name: vpc-flow-logs.json
    files:
      - dashboards/vpc-flow-logs.json

  - name: route53-dns-activity.json
    files:
      - dashboards/route53-dns-activity.json

  - name: kubernetes-views-pods.json
    files:
      - dashboards/kubernetes-views-pods.json

  - name: kubernetes-views-nodes.json
    files:
      - dashboards/kubernetes-views-nodes.json

  - name: kubernetes-system-coredns.json
    files:
      - dashboards/kubernetes-system-coredns.json

  - name: kubernetes-system-apiserver.json
    files:
      - dashboards/kubernetes-system-apiserver.json

  - name: eks-controlplane.json
    files:
      - dashboards/eks-controlplane.json

  - name: cloudtrail-activity-logs.json
    files:
      - dashboards/cloudtrail-activity-logs.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
