apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emojivoto-dev

resources:
  - ../../base
  - ingress.yaml

patches:
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: web
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring

      - op: replace
        path: /spec/namespaceSelector/matchNames/0
        value: emojivoto-dev