apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: online-boutique
    path: ../../microservices-demo/helm-chart
    releaseName: online-boutique
    namespace: PLACEHOLDER_NAMESPACE

resources:
  - metrics-services/
  - servicemonitors/

patches:
  - path: patches/productcatalogservice-metrics-port.yaml
