apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: charts/microservices-demo

helmCharts:
  - name: helm-chart
    releaseName: online-boutique
    namespace: PLACEHOLDER_NAMESPACE
    valuesInline:
      metrics:
        enabled: true

resources:
  - metrics-services/
  - servicemonitors/

patches:
  - target:
      kind: Deployment
      labelSelector: app=productcatalogservice
    path: patches/productcatalogservice-metrics-port.yaml
