apiVersion: v1
kind: Secret
metadata:
  name: repo-workhorse
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/jresmith/workhorse-aws-terraform.git
  username: jresmith
  password: PLACEHOLDER