apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  template:
    spec:
      containers:
        - name: server
          livenessProbe:
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            limits:
              memory: 256Mi
              cpu: 300m
            requests:
              memory: 128Mi
              cpu: 200m
