apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique-dev
resources:
  - ../../base
  - ../../common
  - ingress.yaml

patches:
  - target:
      kind: Service
      name: frontend-external
    patch: |
      - op: add
        path: /metadata/annotations/argocd.ignore-health-check
        value: "true"
