apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: test-secret-seal
  namespace: default
spec:
  encryptedData:
    password: AgAWMzMrnrjuKQcmQCEtrv35OMaVEW7R5gkOBVxaD8T+1CeBpz0BF65hgGDJUeA993bMbw3Uifw9eRR1Jl60m10dEzUhWOG6m4JKivhvfJxBi0+eckbDXazUoJmkP6fg03CMw/tBIIprSyxwlO5roB4qFtQ4bZy8ttKpJFv9OwthZXP0G7R4lKYnoCuoOIU63W8EM1TAbRI+cUrK4hWBOtJiRWRGgrOup8KkJSVIKya4WHTj6/GjtF6Ya7L/Umv8V+m3ZXsurgKOP5nMUb3fA6rboBKtEHB03t4AWFvWxuNMFoQC6NUr46vFfk0BT0qA3G5UW2p/+Geu3mHnRtdg9d+PaHCRpyRk7gOFYnIeGZRbB+Es/R9Ie/IHBWMuODShZBzmZpCri1hvKvoxhWtB6GDOYtoSkL/Rxez5QoPVMZ3cnYds50pV/a/qeEW5qK7rAZ8MLpaeKiuZ13X6DkQzMWzcjdO7B2awXHTgB8xFUwffZnvchnwf1x8D8omjbosWY2xvduuiFZ/N2hESjaL03W/vg1VXBBoMtbvVt5Ez/HHZjw+lVEfOgeGA7SiNU1RugdhnlAzNgvGMrPB0Pgqi8F0p8WxP7ahBvNNBzZj2aKH96v1ISI9LTLJGkg5RdcKbEGvXUeCUz6eKlxyNi7sRXgOauaIjmyfnipTwGmIUsDak7S2JWG82Mj+Pj7IOTOK0FlPCQJzCGMsNlAcafQm3TY0MbBtl7LDA0Q==
  template:
    metadata:
      name: test-secret-seal
      namespace: default
    type: Opaque