---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: test-secret-seal
  namespace: placeholder-web-app-dev
spec:
  encryptedData:
    password: AgAm9v2Urv+xEUyPKmI6FAoEDycteCHkvFmyGGXodTZT3AlrBnQJtU5jSRHhWIS3WK8ZgvhvFz7XGv2b/JNEpbhzlxt+8i28b889La6upcE/f5Dju+kMUcA47xNqgrFkK75qFFeHAwc9HT6lsCVNOA3G6qtEJbI8DK5dV+2ipwdrPiztH2GN/YgWcz/VghH1hBENDitHMFKoSmt9R9iEzLW39t5q+xP40aCjEJPv1gixlu+42IqGq0NvHbCzp7FqvOMhlWz3bgVmIbn6vMyjbeDdLLKWIFReeWM+gyOQ8kAtVqPCZUUUmj/T262ryYg5UuljsfOu1iR3d9AvjbOByOGe4/af3UgYBLC3XHIUzkHd/WIIj128Egv7UzQKUGd53D9opfLByPxpjP8kI0R4ndtJjMICK2UtfsXB+xz53jJLCgR/3PGEPqwKRNMEMfBMzbddOhPfI5ISC00afqOsaYyyAnQzQNGv5gLvQqyJB9hL7As/idti5GfPge1vt9aSjNBmn4YAMvwpD1n4/PzldHNttm6phxU94DFs8jonNtShoFzpMFC6i4R8ItrmJBSBL+xBKM+LISpgzuPN43cTJgKFJdzcLMxUdC9Dg2FOPKd2fWdBTvjsypwtdyRTjdkiWnXqJ9glx+n8ymPHBJuPeiTPaR2oeFImZtfSaFtiYCc+8uMALB2fd/Qc25NW6mPPjbvgZjHfKxw3q2X9yx1rO31JJCEXqWGIZg==
  template:
    metadata:
      name: test-secret-seal
      namespace: placeholder-web-app-dev
    type: Opaque
