apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

helmCharts:
  - name: sealed-secrets
    repo: https://charts.bitnami.com/bitnami
    version: 2.5.19
    releaseName: sealed-secrets
    namespace: kube-system
    valuesFile: values.yaml
