---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook-service-alerts-staging
  namespace: monitoring
spec:
  encryptedData:
    url: AgCqVM2bvXq462LV37ICLktX9PwaWzgWIMdWgR42nfmUI904sqGJL2BUPwcuUkuBnpYq2o7tIwNjdsbd07EeHGtJc/rSepSpwKZ0bLF8c0lNOFRdehz/sUmxBI+ObYhceMxgjQDruMsM4C/tifdM5AtRP7XpLW/AEmD+yFoN0faDj1xNtRuC0yUFVCsQkGmov4mkyaGuSRlNWu/hTDC/6hsjBbWXXtuj4n7z8DKorVoRgVTvFzyiiqHi2CsQyn74FSug+P8OZrx7SgphFJjehZBxiTSLpAwp80h9G4F/y0AvPzgKIfWyC8qZUfWXxBeI/KxcyYXxfD9JzsOv7NETjhdXuJ567N06d2j8D9Ert2z7Wg0sVOk5/i/kOa1GXx7f/RFVleXSxcuKEM2NCmWYA3tx8COKvqj7Q/SFjwVLGvuYv/+W2A733Glr12DFzG3zPAs4P3gerdWKWslfoH88ihp/tU2smbVP2dpGYchDaemhTbCCoK3N0l5RfeuL1LMHT8kuXLPu8fgVY4B7u6ffU4vpdysN1FJJTR4oXO2JRoFKGQqPR2HVBVWQ9mnR0tSlBXt2BzXVOeOPRtR5A0pUOH8Lt1ImsmTdLXt8dRH513v+hJf3UODZXmnXAK0vgLtZjgEmAwsD1CiId6Bw6jADCAJTJhfYdtj2A2nfsoku3fN9nlqsAI44QvPwdl2yY09nC3mQmwIJDEczXQlryRvBhqG07QzpK/f9zI3Ht8obGbTYX/MLftN2vTRvWV04t3rCjmp4wHudUxuoSbmAMUPy6jvzmaeH0zjnUDUuvBxbysNnEm9k
  template:
    metadata:
      name: alertmanager-slack-webhook-service-alerts-staging
      namespace: monitoring
