---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook-platform-alerts-staging
  namespace: monitoring
spec:
  encryptedData:
    url: AgAyN9FdZZ8PnPl/h1OJ6O4ln9GvuPXDEMe+JHWfo/UmHviKV7Q21e52YMqVZATAp1kKjjaQkdHF6Hbn3vLk34WWUSIOJn18N8cmx37ooHLi4luzWc+dSz9hFr705MHfQGJz+rd7p1lfmWbgKjmqEMS83RBcc2Yx8JafBv821eR2EkiTy8ugU8yDDUZa7UnBSh48IO3+S8x/+LNcojJQdhIkxkoVp47zebFh/+3lq+J5BhYLP9I1TfLpEG+o4zG6sTdxZenxWyphLvvwuniM5jYKudfsdwWTei4kqEL3PjeUnDylucQROKNXXEm4Mm/k6Dz3Vpuux9xY2vScDliHAg3lxADDOJI7mleUEpn1zv6dihzrPkHtPBbWqVEV8kuAvJDfoYmUR+lGE8tC6xOMW3FsXBNY25vX6bKDwUK9MVGS1aXGI5Im4M0vG7xnJt/4QFPtGEltJwefGcv4Vms6IOASeKSZqoO1C912lmbzsrHauYb4Fy44oOeGR/JFUsE0DiBM5K/u8ogG2BW5zFywdQ15ZNeSA2GmbtSf4agUIPc+6Kq4rQDVNvaMvjlCNcLE4AX27xG9iMZ6K02rCvbcM7YFGN9Ch3RdlZhBJXMkkJhQ8md8uGkXGzG1UmbSKEmtc88wUJ5B/2VCkmAeBFba4m7q/3Ajr1o8DatwmSD9TJblzWddzj+Y55qvnmZGWXrT9imWqpjPZDGNpKE2Qgcyfv4boUZoeBE1KdeTqtsgL+OZl5v4/Rd5MVI/DzcrnQKhG6L597OgwYnWQKNGBZs5PvwH95VugOrnRT+/tu01cBqsfaxT
  template:
    metadata:
      name: alertmanager-slack-webhook-platform-alerts-staging
      namespace: monitoring
