---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook-slo-alerts-staging
  namespace: monitoring
spec:
  encryptedData:
    url: AgDUoxQGsum1YHJ4ztiD5FPdJhu50DySPYFgmel+H4+LNSqIvpiAqHEGsLiy0FVJHrLW2PvSUldnyGKsE2X1bNr3d3EIUV/4ZG1t2pifrzUyDlaS7nM8BAyMvUgyQjO37TmDXg7KXAMGWJeIlbC4f0xjfEW+sIQ49WwJQkRPb9Q7xoTwXVZuhR7mGNnILLx/HfbZ8i5BJTkYley2G58yUAHMl9W37Nj9aWno4GbmWl1KYKYsxSIZcwzvPwdeyrbOJxwII6CMO/5oOLjoeibQZL4a2ml63sshjhCS+Wa8uapvFhydBxHXNQutRCpdZGBxGTw8nxwOHzlcVRtkGLTval3JA7YZSZ8zvQiEfuAomicFFS7d9rmAPi4WomHbrP4+RMSEHPym1WGc83tBGdfoxWoRJkMC00E8YViZzzKESFZC5Dugv1707X2tv1u46vr384ENUgaIEi09Sr3zwqz2xa8RkfONqsVNxYfPiIBjbSh5IrbPiNSTaD0ALBwiWoohw0rxbRXPdhofYHWX1yzwfivryhnJwWl6hBhkmtBwVrSKOvxnSUFWOn/rYZ/9fsGByyS/xRRP3Ah412311V9mnYHTYLVeN+zfea0ht6/uzRkYsvYm9Ygq90VJLKTumu2lqwAIZDh693ixMYarU4pPAovTBdLw5nwp9uh2upN4SyBdvkkuqq6fZV5g80l9dZ3C2ckl8aSFM7w69aBpZ7owKBifllMeIbU33k1kFojrMfNbT67T02HFqKjlB/Ds3xM/361UCHRxW+7VJqtt1kBOi9BdXTsJ1aRs+jG1OhunAUwO8sfN
  template:
    metadata:
      name: alertmanager-slack-webhook-slo-alerts-staging
      namespace: monitoring
