---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgDDGjlg+zKSNsHj1+hE3VSzrGJtW4swQjebPvHU+Bvhg6d0OPTdNmeD976tDYbGtSWJ/QXdqifuZn2PIEVp/5IF1h5J9flrPHbHxpeuDzYGlCEHoX04Z8xF9vZRd33fzrwejCWTSAPUYFF32QJqE/JjG+l3jtVWZz1+geOF2X64fKzQ3w7ri7UE5coaoQcd6xulzF+vVwelIP8jrx4bmTrDeqW0ae5b0d+rE3sb8gbOsnrJ2KSEbiOZ6gr7/DfxzCW1zZawuo2ii71XGQpVHwclnnvg7BqbPawDzBimIklAKudA1hcuiRVd3Br0srxJGsxwDcsoVJRk8TloSu1j+Pxnj4APIOoCo1uUntvg4Ml0AviJGoL09XV1At8NHGEuxY56gmDHYdp/WFDfPoekyaCWpacj0gIYk6haMXrijfPtjOR+zfwZaWLrS1vimaHaFEpLCFMz1EvV78FKzZwGRkKOunAnWWdO5I+7IW9yI312CtNCtGo6OMCzI6ZJUv+2lgi2AwSiR7a/dLfmA8oSEWbm2cxU6GlnKj2NSkaJR9Wj+reFSaRYfqdxqKQnEwWzi7xXp+qV1tJSBbSqz5SGCknZ9wP0IDYCbwk9jCiBNlEidHvTRjGW7FXOOnvkUHVWI54nSemuU7dVGeSpHORsYGpZnsdrlZ71T/yv9z99O3oIWJ2cPoTcArNiSVpCzc4DkjH7FBR4OCVSZ33pndPc+PNiXRPCnJTtwbcKp3JM9dGmmgR8tBChi6dE2EFa9GhhrSRneqsvK/I5kgGqZbvCoMPuQwV22cd47rczJUgxivLlBrQ=
  template:
    metadata:
      name: alertmanager-slack-webhook
      namespace: monitoring
