configs:
  params:
    controller.diff.server.side: "true"

controller:
  metrics:
    enabled: true

server:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

applicationSet:
  metrics:
    enabled: true

repoServer:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi