apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: placeholder-web-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jresmith/workhorse-aws-terraform.git
    path: workhorse/gitops/placeholder-web-app/overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: placeholder-web-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true