name: Terraform CI

on:
  pull_request:
    paths:
      - "workhorse/terraform/**"
  push:
    branches: ["main"]
    paths:
      - "workhorse/terraform/**"
jobs:
  terraform-ci:
    name: Terraform validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: workhorse/terraform

      - name: Terraform fmt
        working-directory: workhorse/terraform
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: workhorse/terraform
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: workhorse/terraform
        run: terraform validate

      - name: TFLint
        working-directory: workhorse/terraform
        run: tflint --recursive

      - name: Show tfsec version
        run: tfsec --version

      - name: TFsec security scan
        working-directory: workhorse/terraform
        run: tfsec --minimum-severity MEDIUM .

      - name: Terraform plan (no backend)
        working-directory: workhorse/terraform
        env:
          TF_VAR_example: "ci"
        run: terraform plan -lock=false
