apiVersion: v1
kind: Secret
metadata:
  name: repo-creds
  namespace: argocd
  labels: 
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/jresmith/workhorse-aws-terraform.git
  username: jresmith
  # DO NOT PUSH TO GIT - ENCRYPT FIRST
  password: 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 