apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alertmanager-routing-test-prod
  namespace: monitoring
  labels:
    release: kube-prometheus-stack

spec:
  groups:
    - name: receiver-tests
      rules:

        # PROD

        - alert: ProdPlatformReceiverTest
          expr: vector(1)
          for: 1m
          labels:
            environment: prod
            alert_category: platform
            severity: info
          annotations:
            summary: Testing prod platform receiver

        - alert: ProdServiceReceiverTest
          expr: vector(1)
          for: 1m
          labels:
            environment: prod
            alert_category: service
            application: emojivoto
            severity: info
          annotations:
            summary: Testing prod service receiver

        - alert: ProdSLOReceiverTest
          expr: vector(1)
          for: 1m
          labels:
            environment: prod
            alert_category: slo
            application: emojivoto
            slo: request-availability
            severity: info
          annotations:
            summary: Testing prod SLO receiver